spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://81.69.1.254:3306/my_project?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource